# Generated by Django 4.0.1 on 2022-01-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingMalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Malls',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
