# Generated by Django 4.0.1 on 2022-01-26 08:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_product_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
