# Generated by Django 4.0.1 on 2022-01-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_remove_product_demo_link_remove_product_source_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingmalls',
            name='created',
        ),
        migrations.AddField(
            model_name='product',
            name='demo_link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='source_link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vote_ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='vote_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
