# Generated by Django 4.0.1 on 2022-01-26 08:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_remove_shoppingmalls_created_product_demo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingmalls',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='demo_link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='source_link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='vote_ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='vote_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
