# Generated by Django 4.0.1 on 2022-01-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_rename_title_shoppingmalls_title_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingmalls',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
