# Generated by Django 4.0.1 on 2022-01-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_rename_demo_link_shoppingmalls_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingmalls',
            name='product_1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='product_2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='product_3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='product_4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
