# Generated by Django 4.0.1 on 2022-01-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_shoppingmalls_product_1_shoppingmalls_product_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingmalls',
            old_name='product_1',
            new_name='category_1',
        ),
        migrations.RenameField(
            model_name='shoppingmalls',
            old_name='product_2',
            new_name='category_2',
        ),
        migrations.RenameField(
            model_name='shoppingmalls',
            old_name='product_3',
            new_name='category_3',
        ),
        migrations.RenameField(
            model_name='shoppingmalls',
            old_name='product_4',
            new_name='category_4',
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='category_5',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='category_6',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='category_7',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='division',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
