# Generated by Django 4.0.1 on 2022-01-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_rename_product_1_shoppingmalls_category_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingmalls',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
