# Generated by Django 4.0.1 on 2022-01-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0019_alter_shoppingmalls_category_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingmalls',
            name='category_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='category_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='category_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='category_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='category_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='category_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='category_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='other_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='website_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
