# Generated by Django 4.0.1 on 2022-01-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0020_alter_shoppingmalls_category_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingmalls',
            old_name='title_new',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='shoppingmalls',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='shoppingmalls',
            name='vote_total',
        ),
    ]
