# Generated by Django 4.0.1 on 2022-01-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0021_rename_title_new_shoppingmalls_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_10',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_11',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_12',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_13',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_14',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_15',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='facilities_9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
