# Generated by Django 4.0.1 on 2022-01-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0022_shoppingmalls_facilities_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_10',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_11',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_12',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='floors_9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
