# Generated by Django 4.0.1 on 2022-01-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0023_shoppingmalls_floors_1_shoppingmalls_floors_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingmalls',
            name='gmail_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
