# Generated by Django 4.0.1 on 2022-01-27 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0025_shoppingmalls_phone_1_shoppingmalls_phone_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('Brand_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('category_1', models.CharField(blank=True, max_length=200, null=True)),
                ('category_2', models.CharField(blank=True, max_length=200, null=True)),
                ('category_3', models.CharField(blank=True, max_length=200, null=True)),
                ('category_4', models.CharField(blank=True, max_length=200, null=True)),
                ('category_5', models.CharField(blank=True, max_length=200, null=True)),
                ('category_6', models.CharField(blank=True, max_length=200, null=True)),
                ('category_7', models.CharField(blank=True, max_length=200, null=True)),
                ('gmail_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('website_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('other_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_4', models.CharField(blank=True, max_length=50, null=True)),
                ('showrooms_1', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_2', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_3', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_4', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_5', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_6', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_7', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_8', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_9', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_10', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_11', models.CharField(blank=True, max_length=200, null=True)),
                ('showrooms_12', models.CharField(blank=True, max_length=200, null=True)),
                ('division', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='shoppingmalls',
            old_name='image',
            new_name='image_0',
        ),
        migrations.RenameField(
            model_name='shoppingmalls',
            old_name='title',
            new_name='shopping_mall_name',
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='image_1',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='image_2',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='image_3',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='image_4',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
