# Generated by Django 4.0.1 on 2022-01-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0026_brands_rename_image_shoppingmalls_image_0_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
