# Generated by Django 4.0.1 on 2022-01-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0027_delete_feature_delete_product_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='division',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='image',
        ),
        migrations.AddField(
            model_name='brands',
            name='image_0',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='brands',
            name='image_1',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='brands',
            name='image_2',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='brands',
            name='image_3',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='brands',
            name='image_4',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
