# Generated by Django 4.0.1 on 2022-01-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0028_remove_brands_division_remove_brands_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
