# Generated by Django 4.0.1 on 2022-01-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0029_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='Brand_name',
            new_name='brand_name',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='address',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='phone_1',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='phone_3',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='phone_4',
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_13',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_14',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_15',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_16',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_17',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_18',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_19',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_20',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_13',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_14',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_15',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_16',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_17',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_18',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_19',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_20',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='showrooms_phone_9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image_0',
            field=models.ImageField(null=True, upload_to='static/assets/img/brands/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image_1',
            field=models.ImageField(null=True, upload_to='static/assets/img/brands/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image_2',
            field=models.ImageField(null=True, upload_to='static/assets/img/brands/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image_3',
            field=models.ImageField(null=True, upload_to='static/assets/img/brands/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image_4',
            field=models.ImageField(null=True, upload_to='static/assets/img/brands/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_0',
            field=models.ImageField(null=True, upload_to='static/assets/img/malls/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_1',
            field=models.ImageField(null=True, upload_to='static/assets/img/malls/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_2',
            field=models.ImageField(null=True, upload_to='static/assets/img/malls/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_3',
            field=models.ImageField(null=True, upload_to='static/assets/img/malls/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_4',
            field=models.ImageField(null=True, upload_to='static/assets/img/malls/'),
        ),
    ]
