# Generated by Django 4.0.1 on 2022-01-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0030_rename_brand_name_brands_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='showrooms_20',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='showrooms_phone_20',
        ),
    ]
