# Generated by Django 4.0.1 on 2022-01-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0031_remove_brands_showrooms_20_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image_0',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image_1',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
