# Generated by Django 4.0.1 on 2022-01-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0032_alter_brands_image_0_alter_brands_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_0',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
