# Generated by Django 4.0.1 on 2022-01-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0033_alter_brands_image_1_alter_brands_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingmalls',
            name='image_0',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
